//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.CalculatorService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CalculatorService.IWCFCalculator", CallbackContract=typeof(Client.CalculatorService.IWCFCalculatorCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IWCFCalculator {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFCalculator/initializeConnection", ReplyAction="http://tempuri.org/IWCFCalculator/initializeConnectionResponse")]
        void initializeConnection();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFCalculator/initializeConnection", ReplyAction="http://tempuri.org/IWCFCalculator/initializeConnectionResponse")]
        System.Threading.Tasks.Task initializeConnectionAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWCFCalculator/processRequest")]
        void processRequest(string[] request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWCFCalculator/processRequest")]
        System.Threading.Tasks.Task processRequestAsync(string[] request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWCFCalculatorCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWCFCalculator/printMessage")]
        void printMessage(string error);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWCFCalculatorChannel : Client.CalculatorService.IWCFCalculator, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCFCalculatorClient : System.ServiceModel.DuplexClientBase<Client.CalculatorService.IWCFCalculator>, Client.CalculatorService.IWCFCalculator {
        
        public WCFCalculatorClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public WCFCalculatorClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public WCFCalculatorClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public WCFCalculatorClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public WCFCalculatorClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void initializeConnection() {
            base.Channel.initializeConnection();
        }
        
        public System.Threading.Tasks.Task initializeConnectionAsync() {
            return base.Channel.initializeConnectionAsync();
        }
        
        public void processRequest(string[] request) {
            base.Channel.processRequest(request);
        }
        
        public System.Threading.Tasks.Task processRequestAsync(string[] request) {
            return base.Channel.processRequestAsync(request);
        }
    }
}
