//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calculator.CalculatorReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CalculatorReference.IWCFCalculator")]
    public interface IWCFCalculator {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFCalculator/initializeConnection", ReplyAction="http://tempuri.org/IWCFCalculator/initializeConnectionResponse")]
        void initializeConnection();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFCalculator/initializeConnection", ReplyAction="http://tempuri.org/IWCFCalculator/initializeConnectionResponse")]
        System.Threading.Tasks.Task initializeConnectionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFCalculator/processRequest", ReplyAction="http://tempuri.org/IWCFCalculator/processRequestResponse")]
        System.Collections.Generic.Stack<double> processRequest(string request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFCalculator/processRequest", ReplyAction="http://tempuri.org/IWCFCalculator/processRequestResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Stack<double>> processRequestAsync(string request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWCFCalculatorChannel : Calculator.CalculatorReference.IWCFCalculator, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCFCalculatorClient : System.ServiceModel.ClientBase<Calculator.CalculatorReference.IWCFCalculator>, Calculator.CalculatorReference.IWCFCalculator {
        
        public WCFCalculatorClient() {
        }
        
        public WCFCalculatorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WCFCalculatorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFCalculatorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFCalculatorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void initializeConnection() {
            base.Channel.initializeConnection();
        }
        
        public System.Threading.Tasks.Task initializeConnectionAsync() {
            return base.Channel.initializeConnectionAsync();
        }
        
        public System.Collections.Generic.Stack<double> processRequest(string request) {
            return base.Channel.processRequest(request);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Stack<double>> processRequestAsync(string request) {
            return base.Channel.processRequestAsync(request);
        }
    }
}
