//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.CalculatorReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CalculatorReference.IWCFCalculator", CallbackContract=typeof(Client.CalculatorReference.IWCFCalculatorCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IWCFCalculator {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFCalculator/initializeConnection", ReplyAction="http://tempuri.org/IWCFCalculator/initializeConnectionResponse")]
        void initializeConnection();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFCalculator/initializeConnection", ReplyAction="http://tempuri.org/IWCFCalculator/initializeConnectionResponse")]
        System.Threading.Tasks.Task initializeConnectionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFCalculator/processRequest", ReplyAction="http://tempuri.org/IWCFCalculator/processRequestResponse")]
        System.Collections.Generic.Stack<double> processRequest(string request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFCalculator/processRequest", ReplyAction="http://tempuri.org/IWCFCalculator/processRequestResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Stack<double>> processRequestAsync(string request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWCFCalculatorCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWCFCalculator/Error")]
        void Error([System.ServiceModel.MessageParameterAttribute(Name="error")] string error1);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWCFCalculatorChannel : Client.CalculatorReference.IWCFCalculator, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCFCalculatorClient : System.ServiceModel.DuplexClientBase<Client.CalculatorReference.IWCFCalculator>, Client.CalculatorReference.IWCFCalculator {
        
        public WCFCalculatorClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public WCFCalculatorClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public WCFCalculatorClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public WCFCalculatorClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public WCFCalculatorClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void initializeConnection() {
            base.Channel.initializeConnection();
        }
        
        public System.Threading.Tasks.Task initializeConnectionAsync() {
            return base.Channel.initializeConnectionAsync();
        }
        
        public System.Collections.Generic.Stack<double> processRequest(string request) {
            return base.Channel.processRequest(request);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Stack<double>> processRequestAsync(string request) {
            return base.Channel.processRequestAsync(request);
        }
    }
}
